# Generated by Django 5.1.6 on 2026-06-04 02:08

import django.db.models.deletion
import orientacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='orientacion.areaespecialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[orientacion.models.validar_cedula_ecuatoriana])),
                ('nombre_completo', models.CharField(max_length=150)),
                ('area_interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientacion.areaespecialidad')),
                ('especialidad_especifica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientacion.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_habilidades', to='orientacion.especialidad')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='orientacion.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='orientacion.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.pregunta')),
            ],
        ),
    ]
