# Generated by Django 6.0.5 on 2026-05-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.areaespecialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('area_interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientacion.areaespecialidad')),
                ('especialidad_especifica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orientacion.especialidad')),
            ],
        ),
    ]
