# Generated by Django 6.0.5 on 2026-05-11 02:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: PRG-101', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(help_text='Valor ponderado entre 0.0 y 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_materias', to='orientacion.especialidad')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.materia')),
            ],
            options={
                'unique_together': {('especialidad', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(help_text='Calificación sobre 10', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='orientacion.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.materia')),
            ],
            options={
                'unique_together': {('estudiante', 'materia')},
            },
        ),
    ]
