# Generated by Django 6.0.5 on 2026-05-11 03:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientacion', '0002_materia_especialidadmateria_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Lógica Algorítmica, Análisis de Datos, Redes', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='orientacion.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(help_text='Peso de la habilidad entre 0.0 y 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_habilidades', to='orientacion.especialidad')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.habilidad')),
            ],
            options={
                'unique_together': {('especialidad', 'habilidad')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_habilidades', to='orientacion.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacion.pregunta')),
            ],
            options={
                'unique_together': {('estudiante', 'pregunta')},
            },
        ),
    ]
